package TestCorpStage;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

public class Test_settingspage {
	WebDriver driver;


	@Test
	public void launchChrome() throws InterruptedException {

		System.setProperty("webdriver.chrome.driver",
				"C:\\Users\\HP\\eclipse-workspace\\Aumation_V1\\driver\\chromedriver.exe");

		// Creating an object of ChromeDriver
		driver = new ChromeDriver();
		driver.get("https://stageadmin.insmeal.com/login");
		driver.manage().window().maximize();
		Thread.sleep(10000);
		driver.findElement(By.name("email")).sendKeys("goxofomy@teleg.eu");
		driver.findElement(By.name("password")).sendKeys("Byjus.123");
		Thread.sleep(10000);
		driver.findElement(By.xpath("//button[@aria-label='loginButton']")).click();
		Thread.sleep(30000);
		driver.findElement(By.xpath("//p[text () = ' Locked ']")).click();
		Thread.sleep(20000);
		driver.findElement(By.xpath("//input[@placeholder  = 'Write Slug Name Here']")).sendKeys("flash");
		Thread.sleep(20000);
		driver.findElement(By.xpath("//span[ text ()  = 'Submit']")).click();
		Thread.sleep(30000);
		driver.findElement(By.xpath("//span[text() = 'Settings']")).click();
		Thread.sleep(15000);
		driver.findElement(By.xpath("//input[@name = 'restaurant_name']")).sendKeys("1");
		Thread.sleep(15000);
		driver.findElement(By.xpath("//input[@name = 'email_id']")).click();
		Thread.sleep(15000);
		driver.findElement(By.xpath("//input[@name = 'notification_email_id']")).click();
		Thread.sleep(15000);
		driver.findElement(By.xpath("//input[@name = 'phone_number']")).click();
		Thread.sleep(15000);
		driver.findElement(By.xpath("//input[@name = 'alternate_contact_number']")).click();
		Thread.sleep(15000);
		driver.findElement(By.xpath("//p[text () = ' Visible ']")).click();
		Thread.sleep(15000);
		driver.findElement(By.xpath("//input[@name= 'street']")).click();
		Thread.sleep(2500);
		driver.findElement(By.xpath("//input[@name= 'postal_code']")).click();
		Thread.sleep(2500);
		driver.findElement(By.xpath("//input[@name= 'city']")).click();
		Thread.sleep(2500);
		driver.findElement(By.xpath("//input[@name= 'state']")).click();
		Thread.sleep(2500);
		driver.findElement(By.xpath("//input[@name= 'country']")).click();
		Thread.sleep(2500);
		driver.findElement(By.xpath("//span[text ()= 'Add cuisines']")).click();
		Thread.sleep(10000);
		driver.findElement(By.xpath("//input[@id= 'cuisines']")).click();
		Thread.sleep(10000);
		driver.findElement(By.xpath("//span[text ()= 'Cancel']")).click();
//		Thread.sleep(10000);
//		driver.findElement(By.xpath("//span[text ()= 'Add cuisines']")).click();
//		Thread.sleep(10000);
//		driver.findElement(By.xpath("//input[@id= 'cuisines']")).sendKeys("1");
//		Thread.sleep(10000);
//		driver.findElement(By.xpath("//button[text ()= 'Add']")).click();
		Thread.sleep(10000);
		driver.findElement(By.xpath("//span [text ()= 'Next']")).click();
		Thread.sleep(10000);
		driver.findElement(By.xpath("//p[text () = 'Wednesday'][1]")).click();
		Thread.sleep(10000);
		driver.findElement(By.xpath("//p[text () = 'Thursday'][1]")).click();
		Thread.sleep(10000);
		driver.findElement(By.xpath("//button[@ data-testid= 'openingTime0'][1]")).sendKeys("02:02 AM");
		Thread.sleep(10000);
		driver.findElement(By.xpath("//span[ text () = 'OK']")).click();
		Thread.sleep(10000);
		driver.findElement(By.xpath("//button[@ data-testid= 'closingTime0'][1]")).sendKeys("02:02 PM");
		Thread.sleep(10000);
		driver.findElement(By.xpath("//span[ text () = 'OK']")).click();
		Thread.sleep(10000);
		driver.findElement(By.xpath("//input[@ class = 'MuiInputBase-input MuiOutlinedInput-input'][1]")).click();
		Thread.sleep(10000);
		driver.findElement(By.xpath("//input[@ value = '15']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@value = '02']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//div[@id = 'demo-simple-select']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//li[text() = 'One Week']")).click();
        Thread.sleep(10000);
//        driver.findElement(By.xpath("/div[@id = 'demo-simple-select']")).click();
//        Thread.sleep(10000);
//        driver.findElement(By.xpath("//li[text() = 'Two Weeks']")).click();
//        Thread.sleep(10000);
//        driver.findElement(By.xpath("/div[@id = 'demo-simple-select']")).click();
//        Thread.sleep(10000);
//        driver.findElement(By.xpath("//li[text() = 'One Month']")).click();
//        Thread.sleep(10000);
//        driver.findElement(By.xpath("/div[@id = 'demo-simple-select']")).click();
//        Thread.sleep(10000);
//        driver.findElement(By.xpath("//li[text() = 'Two Days']")).click();
//        Thread.sleep(10000);
//        driver.findElement(By.xpath("//span[@class ='MuiSwitch-thumb jss188']")).click();
//        Thread.sleep(10000);
//        driver.findElement(By.xpath("//span[@class ='MuiSwitch-thumb jss188']")).click();
//        Thread.sleep(10000);
     //   driver.findElement(By.xpath("//div[@class = 'jss1144']")).click();
     //   Thread.sleep(10000);
    //    driver.findElement(By.xpath("//textarea[@placeholder ='zip seperated with commas eg. zip1, zip2..']")).sendKeys("125125");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text() ='Delivery Only']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text() ='Pickup Only']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text() ='Both Delivery and Pickup']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//span[text() ='Add new Fee']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name ='name']")).sendKeys("CV");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name ='value']")).sendKeys("5");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//div[text() ='Dollar($)']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//li[text() ='Percentage(%)']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//button[@data-testid= 'saveCharge']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//button[@data-testid= 'dynamic_delivery_charge_btn']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//button[@data-testid= 'add_new_dynamic_delivery_charge']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'distance']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'charges']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//button[@data-testid= 'delete_dynamic_delivery_charge_0']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//button[@data-testid= 'add_new_dynamic_delivery_charge']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'distance']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'charges']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//button[@data-testid= 'save_Dynamic_delivery_charges_btn']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//span[text() = 'Add New Delivery Charge']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'name']")).sendKeys("ASDF");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'value']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//div[@id = 'mui-component-select-type']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//li[@data-value= '%']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//button[@data-testid= 'saveCharge']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//span[text() = 'Add New PickUp Charge']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'name']")).sendKeys("ASDF");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'value']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//div[@id = 'mui-component-select-type']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//li[@data-value= '%']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//button[@data-testid= 'saveCharge']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'enableMinimumOrder']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'minimumOrderDelivery']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'minimumOrderPickup']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'enableMaximumOrder']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'maximumOrderDelivery']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'maximumOrderPickup']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@aria-label= 'deliveryInitialDelay']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@aria-label= 'deliveryInterval']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@aria-label= 'pickupInitialDelay']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@aria-label= 'pickupInterval']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@aria-label= 'deliveryRadius']")).sendKeys("08");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'enableTaxes']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//span[text() = 'Add new Tax']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'value']")).sendKeys("05");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'name']")).sendKeys("ASDF");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//div[@id= 'mui-component-select-type']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//li[@data-value= '%']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//button[@data-testid = 'saveCharge']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text() = 'Yes, I will enter prices inclusive of tax']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text() = 'No, I will enter prices exclusive of tax']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//span[text( )= 'Add new Tip']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@aria-label = 'taxName']")).sendKeys("asdf");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@aria-label = 'taxValue']")).sendKeys("20");
        Thread.sleep(10000);
        driver.findElement(By.xpath("//button[@data-testid= 'saveCharge']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text()= 'Confirm address from user before checkout']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text()= 'Enable Instructions']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text()= 'Required Billing Info']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//span[text()= 'Next']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text()= 'Pay By Cash']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text()= 'Pay By Card']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text()= 'Pay By Cash']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//p[text()= 'Pay By Card']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'discover']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'mastercard']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'visa']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'american_express']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'discover']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'mastercard']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'visa']")).click();
        Thread.sleep(10000);
        driver.findElement(By.xpath("//input[@name= 'american_express']")).click();
      //  Thread.sleep(10000);
      //  driver.findElement(By.xpath("Save")).click();
        
		
		

	}

}
